controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

# homepage
app_page:
  path: /
  controller: App\Controller\HomepageController::home


# route pour les catégories
# config/routes.yaml
app_category:
  path: "/category/{id}"
  controller: App\Controller\CategoryController::categoryAction

# route pour les bonbons par categorie

sweets_by_category:
  path: "/category/{id}"
  controller: App\Controller\SweetsController::categorySweets

# route pour le detail du bonbon
product_detail:
  path: "/product/{id}"
  controller: App\Controller\ProductController::detail

# route pour le panier
add_to_cart:
  path: /add-to-cart/{sweetId}
  controller: App\Controller\CartController::addToCart

# route pour la connexion/deconnexion
login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout


# route pour register 
register:
    path: /register
    controller: App\Controller\RegistrationController::register


# route admin dash
admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
  
    # requirements:
    #     _role: ROLE_ADMIN


# route recherche
search:
    path: /search
    controller: App\Controller\SweetsController::searchAction

# route pour validation de commande 

order_validate:
    path: '/order/validate'
    controller: 'App\Controller\OrderController::validate'

# pour le total de cde
order_validation:
    path: /order/validate
    controller: App\Controller\OrderController::validationCommande
    
